### post comment

POST localhost:9090/comment
Content-Type: application/json

{
  "songId": 3,
  "content": "sss",
  "parentCommentId": null
}

### get all comments by song id

GET localhost:9090/songs/1/comments
Content-Type: application/json

### like comment

POST localhost:9090/comments/9/like
Content-Type: application/json

### unlike comment

DELETE localhost:9090/comments/8/like
Content-Type: application/json

### edit comment

PUT localhost:9090/comments/12/edit
Content-Type: application/json

{
  "content" : "abv"
}

### delete comment

DELETE localhost:9090/comments/1
Content-Type: application/json