POST localhost:9090/create_playlist
Content-Type: application/json

{
  "title": "mymc",
  "is_public": 0
  }

### like a playlist
POST localhost:9090/playlists/2/like
Content-Type: application/json

### unlike playlist
DELETE localhost:9090/playlists/1/unlike
Content-Type: application/json



### add song to playlist
POST localhost:9090/playlists/add_song?playlistId=1&songId=1
Content-Type: application/json

### delete song from playlist
DELETE localhost:9090/playlists/delete_song?playlistId=1&songId=12
Content-Type: application/json

### get playlist by id

GET localhost:9090/playlists/1
Content-Type: application/json

### get playlist by title
GET localhost:9090/playlists/find-by-title/h
Content-Type: application/json

### order playlist by likes
GET localhost:9090/playlists/order-by-likes/?id=acs

### delete playlist
DELETE localhost:9090/playlists/1
Content-Type: application/json

### edit playlist
PUT localhost:9090/playlists/edit
Content-Type: application/json

{
"id": 2,
"title": "half life",
"isPublic": true
}
