POST localhost:9090/create_playlist
Content-Type: application/json

{
  "title": "newer",
  "is_public": 1
  }

### like a playlist
POST localhost:9090/playlists/1/like
Content-Type: application/json

### unlike playlist
DELETE localhost:9090/playlists/1/unlike
Content-Type: application/json



### add song to playlist
POST localhost:9090/playlists/add_song?playlistId=1&songId=12
Content-Type: application/json

