### upload song

POST localhost:9090/upload_song
Content-Type: application/json

{
  "title": "smule",
  "isPublic": true,
  "description": {
    "content": "hi #try #neww"
  }
}
###
POST localhost:9090/upload_song
Content-Type: application/json

{
"title": "hev",
"songUrl": "dfg",
"isPublic": true,
"description": null
}

###
POST localhost:9090/upload_song
Content-Type: application/json

{
  "title": "heaven",
  "songUrl": "dfg",
  "isPublic": false,
  "description": null
}

### find all by owner id, ordered by upload time

GET localhost:9090/users/1/songs
Content-Type: application/json


### like a song
POST localhost:9090/songs/1/like
Content-Type: application/json

### unlike a song
DELETE localhost:9090/songs/2/unlike
Content-Type: application/json

### get song by name
GET localhost:9090/songs/ghost
Content-Type: application/json

### edit song

PUT localhost:9090/songs/edit
Content-Type: application/json

{
  "id": 10,
  "title": "new",
  "isPublic": false,
  "description": {
    "content": "  "
  }
}

### play a song

GET localhost:9090/songs/26/play
Content-Type: application/json

### stop a song

GET localhost:9090/songs/stop
Content-Type: application/json

### get songs using pagination & sorting of field of song

GET localhost:9090/paginationAndSort/0/3/title
Content-Type: application/json


