### upload song

POST localhost:9090/upload_song
Content-Type: application/json

{
  "title": "ghost",
  "songUrl": "djfj",
  "coverPhotoUrl": null,
  "isPublic": true,
  "description": {
    "content": "hi #tag #new"
  }
}
###
POST localhost:9090/upload_song
Content-Type: application/json

{
"title": "miss",
"songUrl": "dfg",
"coverPhotoUrl": null,
"isPublic": true,
"description": null
}

### find all by owner id, ordered by upload time

GET localhost:9090/users/13/songs
Content-Type: application/json


### like a song
POST localhost:9090/songs/2/like
Content-Type: application/json

### unlike a song
DELETE localhost:9090/songs/2/unlike
Content-Type: application/json

### get song by name
GET localhost:9090/songs/ghost
Content-Type: application/json
