### login

POST localhost:9090/login
Content-Type: application/json

{
  "username" : "user33",
  "password" : "newP@ss1"
}

###
POST localhost:9090/login
Content-Type: application/json

{

"username" : "nel",
"password" : "1P@ssword"

}


###
POST localhost:9090/login
Content-Type: application/json

{
  "username" : "nnnn",
  "password" : "1P@ssword"
}

### register
POST localhost:9090/register
Content-Type: application/json

{
  "username": "nnn",
  "email": "email@gmailll.com" ,
  "password": "1P@ssword",
  "confirmedPassword": "1P@ssword",
  "age": 14,
  "gender": "f"
}

###
POST localhost:9090/register
Content-Type: application/json

{
  "username": "Veronika",
  "email": "veronikatodorovva@gmail.com",
  "password": "1P@ssword",
  "confirmedPassword": "1P@ssword",
  "age": 14,
  "gender": "f"
}

### change password

PUT localhost:9090/password
Content-Type: application/json

{
  "oldPassword" : "3P@ssword",
  "newPassword" : "4P@ssword",
  "confirmedPassword": "4P@ssword"
}

### edit user

PUT localhost:9090/edit
Content-Type: application/json

{
"username": "nnnn",
"email": "nelinaa@gmail.com",
"age": 14,
"gender": "F"
}

### get user by id

GET localhost:9090/users/13
Content-Type: application/json

### follow user

POST localhost:9090/users/1/follow
Content-Type: application/json

### get following

GET localhost:9090/users/13/following
Content-Type: application/json

### get followers

GET localhost:9090/users/13/followers

### find user by username

GET localhost:9090/find-by-username/Ivan
Content-Type: application/json

### logout

POST localhost:9090/logout
Content-Type: application/json

### delete user by id
DELETE localhost:9090/delete-user/1
Content-Type: application/json