### login

POST localhost:9090/login
Content-Type: application/json

{
  "username" : "user33",
  "password" : "newP@ss1"
}

###
POST localhost:9090/login
Content-Type: application/json

{
"username" : "nnnn",
"password" : "3P@ssword"
}


###
POST localhost:9090/login
Content-Type: application/json

{
  "username" : "nnn",
  "password" : "1P@ssword"
}

### register
POST localhost:9090/register
Content-Type: application/json

{
  "username": "nnnn",
  "email": "email@gmailll.com" ,
  "password": "1P@ssword",
  "confirmedPassword": "1P@ssword",
  "age": 14,
  "gender": null
}

###
POST localhost:9090/register
Content-Type: application/json

{
  "username": "nel",
  "email": "nel@gmailll.com" ,
  "password": "1P@ssword",
  "confirmedPassword": "1P@sswoRrd",
  "age": 14,
  "gender": null
}

### change password

PUT localhost:9090/password
Content-Type: application/json

{
  "oldPassword" : "2P@ssword",
  "newPassword" : "3P@ssword",
  "confirmedPassword": "3P@ssword"
}

### edit user

PUT localhost:9090/edit
Content-Type: application/json

{
"username": "nnnn",
"email": "nelina@gmail.com",
"age": 14,
"gender": "F",
"profilePictureUrl": null
}

### get user by id

GET localhost:9090/users/13
Content-Type: application/json


### find user by username

GET localhost:9090/find-by-username/Ivan
Content-Type: application/json

### logout

POST localhost:9090/logout
Content-Type: application/json

